name: Build in Ubuntu-22.04 (Docker)

on:
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04

    steps:
      -
        name: Check out repository
        uses: actions/checkout@v3
      -
        name: remotes and rprojroot
        run: R ${PWD}/tools/000.R
      -
        name: system dependencies
        run: bash ${PWD}/tools/dep.sh
      -
        name: R dependencies
        run: R ${PWD}/tools/dep.R
      -
        name: build package
        run: bash ${PWD}/tools/build.sh
